### ---------- GET requests --------------
GET http://localhost:2020/

###

GET http://localhost:2020/api/projects

###

GET http://localhost:2020/api/projects/1

###

GET http://localhost:2020/api/actions

###

GET http://localhost:2020/api/actions/3

### -------------- POST requests ----------------

### New project
POST http://localhost:2020/api/projects
content-type: application/json

{
    "name": "Another new project",
    "description": "...for a new day.",
    "completed": false
}

###
POST http://localhost:2020/api/actions/
content-type: application/json

{
    "project_id": 1,
    "description": "Be Happy.",
    "notes": "Turn that frown upside down.",
    "completed": false
}

### ------------ DELETE requests ----------------
DELETE http://localhost:2020/api/projects/2

###
DELETE http://localhost:2020/api/actions/15